# Dockerfile.consumer для сервисa consumer (Go)
FROM golang:1.24-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o consumer cmd/consumer/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/consumer .
COPY --from=builder /app/migrations/clickhouse ./migrations/clickhouse
# команда запуска consumer
CMD ["./consumer"]
